name: Assign issue
on: push

jobs:
  assign:
    name: Take an issue
    runs-on: ubuntu-latest
    steps:
    - name: take the issue
      uses: HarikiranGit/Docker-Action@main
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        message: Thanks for taking this issue! Let us know if you have any questions!
        trigger: .take
